format_us_states = [
    "bar harbor,Maine",
    "satitoa,American Samoa",
    "redlands,Utah",
    "rapid valley,South Dakota",
    "ojinaga,Texas",
    "cutler,Florida",
    "montrose,Colorado",
    "cedar city,Utah",
    "moab,Utah",
    "price,Utah",
    "carlsbad,New Mexico",
    "isla vista,California",
    "forest acres,South Carolina",
    "klamath falls,Oregon",
    "macedonia,Ohio",
    "ridgecrest,Califonia",
    "anchorage,Alaska",
    "key west,Florida",
    "homestead,Florida",
    "barrow,Alaska",
    "saint louis,Missouri",
    "cardston,Montana",
    "haines junction,Alaska",
    "flagstaff,Arizona",
    "jackson,Wyoming",
    "west wendover,Nevada",
    "alamosa,Colorado",
    "sevierville,Tennessee",
    "pine springs,Texas",
    "kihei,Hawaii",
    "hilo,Hawaii",
    "hot springs,Arizona",
    "chesterton,Indiana",
    "thunder bay,Michigan",
    "twentynine palms,Califonia",
    "kodiak,Alaska",
    "sterling,Alaska",
    "orange cove,Califonia",
    "kiana,Alaska",
    "homer,Alaska",
    "magalia,Califonia",
    "glasgow,Kentucky",
    "cortez,Colorado",
    "enumclaw,Washington",
    "hope,Washington",
    "port angeles,Washington",
    "show low,Arizona",
    "soledad,Califonia",
    "arcata,Califonia",
    "boulder,Colorado",
    "marana,Arizona",
    "exeter,Califonia",
    "harrisonburg,Virginia",
    "dickinson,North Dakota",
    "coral bay,U.S.Virgin Islands",
    "fort frances,Minnesota",
    "alamogordo,New Mexico",
    "rapid city,South Dakota",
    "mccarthy,Alaska",
    "canyon village,Wyoming",
    "chowchilla,Califonia",
    "hurricane,Utah"
]