all_csv = [
	'alamogordo,New Mexico.csv',
	'anchorage,Alaska.csv',
	'bar harbor,Maine.csv',
	'barrow,Alaska.csv',
	'boulder,Colorado.csv',
	'canyon village,Wyoming.csv',
	'cardston,Montana.csv',
	'carlsbad,New Mexico.csv',
	'chesterton,Indiana.csv',
	'chowchilla,Califonia.csv',
	'coral bay,U.S.VirginIslands.csv',
	'cortez,Colorado.csv',
	'dickinson,North Dakota.csv',
	'exeter,Califonia.csv',
	'forest acres,South Carolina.csv',
	'fort frances,Minnesota.csv',
	'glasgow,Kentucky.csv',
	'harrisonburg,Virginia.csv',
	'hilo,Hawaii.csv',
	'homer,Alaska.csv',
	'homestead,Florida.csv',
	'hope,Washington.csv',
	'hot springs,Arizona.csv',
	'hurricane,Utah.csv',
	'isla vista,California.csv',
	'jackson,Wyoming.csv',
	'kiana,Alaska.csv',
	'kihei,Hawaii.csv',
	'klamath falls,Oregon.csv',
	'kodiak,Alaska.csv',
	'macedonia,Ohio.csv',
	'marana,Arizona.csv',
	'pine springs,Texas.csv',
	'port angeles,Washington.csv',
	'rapid city,South Dakota.csv',
	'saint louis,Missouri.csv',
	'soledad,Califonia.csv',
	'sterling,Alaska.csv',
	'terlingua,Texas.csv',
	'thunder bay,Michigan.csv',
	'west wendover,Nevada.csv',
	'alamosa,Colorado.csv',
	'arcata,California.csv',
	'cedar city,Utah.csv',
	'cutler,Florida.csv',
	'enumclaw,Washington.csv',
	'flagstaff,Arizona.csv',
	'haines junction,Alaska.csv',
	'key west,Florida.csv',
	'magalia,California.csv',
	'moab,Utah.csv',
	'montrose,Colorado.csv',
	'orange cove,California.csv',
	'price,Utah.csv',
	'rapid valley,South Dakota.csv',
	'redlands,Utah.csv',
	'ridgecrest,California.csv',
	'sevierville,Tennessee.csv',
	'show low,Arizona.csv',
	'twentynine palms,California.csv'
]