all_csv = [
	'alamogordo,New Mexico.csv',
	'alamosa,Colorado.csv',
	'anchorage,Alaska.csv',
	'arcata,California.csv',
	'bar harbor,Maine.csv',
	'barrow,Alaska.csv',
	'boulder,Colorado.csv',
	'canyon village,Wyoming.csv',
	'cardston,Montana.csv',
	'carlsbad,New Mexico.csv',
	'cedar city,Utah.csv',
	'chesterton,Indiana.csv',
	'chowchilla,Califonia.csv',
	'coral bay,U.S.VirginIslands.csv',
	'cortez,Colorado.csv',
	'cutler,Florida.csv',
	'dickinson,North Dakota.csv',
	'enumclaw,Washington.csv',
	'exeter,Califonia.csv',
	'flagstaff,Arizona.csv',
	'forest acres,South Carolina.csv',
	'fort frances,Minnesota.csv',
	'glasgow,Kentucky.csv',
	'haines junction,Alaska.csv',
	'harrisonburg,Virginia.csv',
	'hilo,Hawaii.csv',
	'homer,Alaska.csv',
	'homestead,Florida.csv',
	'hope,Washington.csv',
	'hot springs,Arizona.csv',
	'hurricane,Utah.csv',
	'isla vista,California.csv',
	'jackson,Wyoming.csv',
	'key west,Florida.csv',
	'kiana,Alaska.csv',
	'kihei,Hawaii.csv',
	'klamath falls,Oregon.csv',
	'kodiak,Alaska.csv',
	'macedonia,Ohio.csv',
	'magalia,California.csv',
	'marana,Arizona.csv',
	'moab,Utah.csv',
	'montrose,Colorado.csv',
	'orange cove,California.csv',
	'pine springs,Texas.csv',
	'port angeles,Washington.csv',
	'price,Utah.csv',
	'rapid city,South Dakota.csv',
	'rapid valley,South Dakota.csv',
	'redlands,Utah.csv',
	'ridgecrest,California.csv',
	'saint louis,Missouri.csv',
	'sevierville,Tennessee.csv',
	'show low,Arizona.csv',
	'soledad,Califonia.csv',
	'sterling,Alaska.csv',
	'terlingua,Texas.csv',
	'thunder bay,Michigan.csv',
	'twentynine palms,California.csv',
	'west wendover,Nevada.csv'
]