states_by_park = [
    'Maine',
    'American Samoa',
    'Utah',
    'South Dakota',
    'Texas',
    'Florida',
    'Colorado',
    'Utah',
    'Utah',
    'Utah',
    'New Mexico',
    'California',
    'South Carolina',
    'Oregon',
    'Ohio',
    'Califonia',
    'Alaska',
    'Florida',
    'Florida',
    'Alaska',
    'Missouri',
    'Montana',
    'Alaska',
    'Arizona',
    'Wyoming',
    'Nevada',
    'Colorado',
    'Tennessee',
    'Texas',
    'Hawaii',
    'Hawaii',
    'Arizona',
    'Indiana',
    'Michigan',
    'Califonia',
    'Alaska',
    'Alaska',
    'Califonia',
    'Alaska',
    'Alaska',
    'Califonia',
    'Kentucky',
    'Colorado',
    'Washington',
    'Washington',
    'Washington',
    'Arizona',
    'Califonia',
    'Califonia',
    'Colorado',
    'Arizona',
    'Califonia',
    'Virginia',
    'North Dakota',
    'U.S.VirginIslands',
    'Minnesota',
    'New Mexico',
    'South Dakota',
    'Alaska',
    'Wyoming',
    'Califonia',
    'Utah'
]